-- SELECT TABLES 
SELECT * FROM TRANSACTIONS;
SELECT * FROM CUSTOMERS;
SELECT * FROM LOCATION;

--DROP TABLES 
-- DROP TABLE TRANSACTIONS;
-- DROP TABLE CUSTOMERS;
-- DROP TABLE LOCATION;

CREATE TABLE LOCATION (
    location_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    lat NUMBER(10, 6),
    longitude NUMBER(10, 6),
    city_pop NUMBER,
    city VARCHAR2(255),
    state VARCHAR2(255),
    zip VARCHAR2(255),
    street VARCHAR2(255),
    CONSTRAINT location_pk PRIMARY KEY (location_id)
);

CREATE TABLE CUSTOMERS (
    cc_num VARCHAR2(255) PRIMARY KEY,
    location_id NUMBER,
    first_name VARCHAR2(255),
    last_name VARCHAR2(255),
    gender VARCHAR2(255),
    job VARCHAR2(255),
    dob DATE,
    CONSTRAINT customers_location_fk FOREIGN KEY (location_id) REFERENCES LOCATION (location_id)
);

CREATE TABLE TRANSACTIONS (
    trans_num VARCHAR2(255) PRIMARY KEY,
    cc_num VARCHAR2(255),
    trans_date TIMESTAMP,
    amt NUMBER(18, 2),
    unix_time VARCHAR2(255),
    merchant VARCHAR2(255),
    category VARCHAR2(255),
    merch_lat NUMBER(10, 6),
    merch_long NUMBER(10, 6),
    CONSTRAINT transactions_customers_fk FOREIGN KEY (cc_num) REFERENCES CUSTOMERS (cc_num)
);

